# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/dron/Games4Linux/code_files/untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.ApplicationModal)
        MainWindow.resize(720, 538)
        MainWindow.setMinimumSize(QtCore.QSize(720, 538))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(71, 71, 71))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 170, 170))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(71, 71, 71))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(71, 71, 71))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(71, 71, 71))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 170, 170))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(71, 71, 71))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(71, 71, 71))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(71, 71, 71))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 170, 170))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(71, 71, 71))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(71, 71, 71))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.PlaceholderText, brush)
        MainWindow.setPalette(palette)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/newPrefix/img/logonew.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("background-color: rgb(71, 71, 71);\n"
"")
        MainWindow.setUnifiedTitleAndToolBarOnMac(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setStyleSheet("QTabBar::tab:selected{\n"
"background-color: rgb(48, 48, 48);\n"
"color: rgb(255, 255, 255);\n"
"}\n"
"QTabBar::tab:hover {}\n"
"QTabBar{\n"
"background-color:rgb(255, 16, 72);\n"
"border-top-left-radius: 8px;\n"
"border-bottom-left-radius: 8px;\n"
"color: rgb(255, 255, 255);\n"
"font:  11pt;\n"
"}\n"
"QToolButton{\n"
"background-color: transparent;\n"
"border:none;\n"
"font:  11pt;\n"
"font-weight:900;\n"
"color: rgb(255, 255, 255);\n"
"}\n"
"QTabWidget{\n"
"background-color: rgb(48, 48, 48);\n"
"border:none;\n"
"}\n"
"QTabBar::tab {\n"
"    background-color: rgb(255, 16, 72);\n"
"    border-top-left-radius: 8px;\n"
"    border-bottom-left-radius: 8px;\n"
"    padding-bottom:13px;\n"
"    padding-top:13px;\n"
"    padding-left:4px;\n"
"    padding-right:4px;\n"
"    border:15px;\n"
"}\n"
"\n"
"")
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.tabWidget.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.tabWidget.setAutoFillBackground(False)
        self.tabWidget.setStyleSheet("")
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.West)
        self.tabWidget.setIconSize(QtCore.QSize(35, 40))
        self.tabWidget.setUsesScrollButtons(True)
        self.tabWidget.setDocumentMode(False)
        self.tabWidget.setTabsClosable(False)
        self.tabWidget.setMovable(True)
        self.tabWidget.setTabBarAutoHide(False)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setStyleSheet("background-color: rgb(48, 48, 48);")
        self.tab.setObjectName("tab")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.tabWidget_2 = QtWidgets.QTabWidget(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget_2.sizePolicy().hasHeightForWidth())
        self.tabWidget_2.setSizePolicy(sizePolicy)
        self.tabWidget_2.setStyleSheet("QTabBar{\n"
"background-color:rgb(255, 16, 72);\n"
"}")
        self.tabWidget_2.setTabPosition(QtWidgets.QTabWidget.West)
        self.tabWidget_2.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget_2.setIconSize(QtCore.QSize(0, 0))
        self.tabWidget_2.setElideMode(QtCore.Qt.ElideNone)
        self.tabWidget_2.setObjectName("tabWidget_2")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.tab_5)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.groupBox_4 = QtWidgets.QGroupBox(self.tab_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_4.sizePolicy().hasHeightForWidth())
        self.groupBox_4.setSizePolicy(sizePolicy)
        self.groupBox_4.setStyleSheet("background-color: rgb(71, 71, 71);\n"
"font:11pt;\n"
"font-weight:900;\n"
"border-radius:13px;\n"
"padding:7px;\n"
"\n"
"")
        self.groupBox_4.setTitle("")
        self.groupBox_4.setObjectName("groupBox_4")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.groupBox_4)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.toolButton_8 = QtWidgets.QToolButton(self.groupBox_4)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/newPrefix/img/cross.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_8.setIcon(icon1)
        self.toolButton_8.setIconSize(QtCore.QSize(13, 13))
        self.toolButton_8.setObjectName("toolButton_8")
        self.gridLayout_11.addWidget(self.toolButton_8, 0, 1, 1, 1)
        self.toolButton_9 = QtWidgets.QToolButton(self.groupBox_4)
        self.toolButton_9.setStyleSheet("QToolButton{\n"
"border-radius:16px;\n"
"background-color: rgb(255, 16, 72);\n"
"border:none;\n"
"font:  11pt;\n"
"}")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/newPrefix/img/search-3-16.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_9.setIcon(icon2)
        self.toolButton_9.setObjectName("toolButton_9")
        self.gridLayout_11.addWidget(self.toolButton_9, 0, 2, 1, 1)
        self.lineEdit_4 = QtWidgets.QLineEdit(self.groupBox_4)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(71, 71, 71))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(71, 71, 71))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(71, 71, 71))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(71, 71, 71))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(71, 71, 71))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(71, 71, 71))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(71, 71, 71))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(71, 71, 71))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(71, 71, 71))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.PlaceholderText, brush)
        self.lineEdit_4.setPalette(palette)
        self.lineEdit_4.setStyleSheet("border: 1px 1px 0px 1px;\n"
"color: rgb(255, 255, 255);\n"
"")
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.gridLayout_11.addWidget(self.lineEdit_4, 0, 0, 1, 1)
        self.listWidget_3 = QtWidgets.QListWidget(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listWidget_3.sizePolicy().hasHeightForWidth())
        self.listWidget_3.setSizePolicy(sizePolicy)
        self.listWidget_3.setMinimumSize(QtCore.QSize(486, 0))
        self.listWidget_3.setToolTipDuration(0)
        self.listWidget_3.setStyleSheet("QScrollBar:vertical {\n"
"background-color: transparent;\n"
"width: 25px;\n"
"margin: 0px 0px 0px 0px;\n"
"}\n"
"QScrollBar::handle:vertical {\n"
"border-radius: 5px;\n"
"background: rgb(48, 48, 48);\n"
"min-height: 48px;\n"
"}\n"
"\n"
"/* This remvoes the bottom button by setting the height to 0px */\n"
"QScrollBar::add-line:vertical {\n"
"height: 0px;\n"
"subcontrol-position: bottom;\n"
"subcontrol-origin: margin;\n"
"}\n"
"\n"
"/* This remvoes the top button by setting the height to 0px */\n"
"QScrollBar::sub-line:vertical {\n"
"height: 0px;\n"
"subcontrol-position: top;\n"
"subcontrol-origin: margin;\n"
"}\n"
"\n"
"/* need this to get rid of crosshatching on scrollbar background */\n"
"QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"background: none;\n"
"}\n"
"QListWidget{\n"
"color:rgb(255, 255, 255);\n"
"background-color: rgb(71, 71, 71);\n"
"font:11pt;\n"
"font-weight:900;\n"
"border:none;\n"
"border-radius:13px;\n"
"padding:5px;\n"
"\n"
"}\n"
"QListWidget::item::selected{\n"
"padding:-0px;\n"
"border-radius:7px;\n"
"background-color:  rgb(255, 16, 72);\n"
"color:rgb(255, 255, 255);\n"
"}\n"
"QListWidget::item{\n"
"padding:5px;\n"
"color:rrgb(255, 16, 72);\n"
"}")
        self.listWidget_3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.listWidget_3.setEditTriggers(QtWidgets.QAbstractItemView.DoubleClicked|QtWidgets.QAbstractItemView.EditKeyPressed|QtWidgets.QAbstractItemView.SelectedClicked)
        self.listWidget_3.setProperty("showDropIndicator", False)
        self.listWidget_3.setIconSize(QtCore.QSize(13, 13))
        self.listWidget_3.setGridSize(QtCore.QSize(15, 35))
        self.listWidget_3.setViewMode(QtWidgets.QListView.ListMode)
        self.listWidget_3.setModelColumn(0)
        self.listWidget_3.setUniformItemSizes(True)
        self.listWidget_3.setWordWrap(False)
        self.listWidget_3.setObjectName("listWidget_3")
        self.gridLayout_11.addWidget(self.listWidget_3, 1, 0, 1, 3)
        self.gridLayout_5.addWidget(self.groupBox_4, 0, 0, 8, 1)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.toolButton_10 = QtWidgets.QToolButton(self.tab_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolButton_10.sizePolicy().hasHeightForWidth())
        self.toolButton_10.setSizePolicy(sizePolicy)
        self.toolButton_10.setMinimumSize(QtCore.QSize(100, 40))
        self.toolButton_10.setStyleSheet("QToolButton::checked{\n"
"border-radius:5px;\n"
"background-color: rgb(255, 16, 72);\n"
"}")
        self.toolButton_10.setCheckable(True)
        self.toolButton_10.setAutoRepeat(True)
        self.toolButton_10.setAutoExclusive(True)
        self.toolButton_10.setObjectName("toolButton_10")
        self.verticalLayout_3.addWidget(self.toolButton_10)
        self.toolButton_7 = QtWidgets.QToolButton(self.tab_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolButton_7.sizePolicy().hasHeightForWidth())
        self.toolButton_7.setSizePolicy(sizePolicy)
        self.toolButton_7.setMinimumSize(QtCore.QSize(100, 40))
        self.toolButton_7.setStyleSheet("QToolButton::checked{\n"
"border-radius:5px;\n"
"background-color: rgb(255, 16, 72);\n"
"}")
        self.toolButton_7.setCheckable(True)
        self.toolButton_7.setAutoRepeat(True)
        self.toolButton_7.setAutoExclusive(True)
        self.toolButton_7.setObjectName("toolButton_7")
        self.verticalLayout_3.addWidget(self.toolButton_7)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem)
        self.gridLayout_5.addLayout(self.verticalLayout_3, 0, 1, 1, 1)
        self.tabWidget_2.addTab(self.tab_5, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.tab_3)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.gridLayout_9 = QtWidgets.QGridLayout()
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.Installscript = QtWidgets.QToolButton(self.tab_3)
        self.Installscript.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Installscript.sizePolicy().hasHeightForWidth())
        self.Installscript.setSizePolicy(sizePolicy)
        self.Installscript.setStyleSheet("QToolButton::checked{\n"
"border-radius:5px;\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:1, x2:1, y2:1, stop:0 rgba(255, 129, 25, 255), stop:1 rgba(255, 0, 0, 255));\n"
"}")
        self.Installscript.setIconSize(QtCore.QSize(40, 40))
        self.Installscript.setCheckable(True)
        self.Installscript.setAutoExclusive(True)
        self.Installscript.setObjectName("Installscript")
        self.gridLayout_9.addWidget(self.Installscript, 0, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_9.addItem(spacerItem1, 3, 1, 1, 1)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.comboBox_2 = QtWidgets.QComboBox(self.tab_3)
        self.comboBox_2.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_2.sizePolicy().hasHeightForWidth())
        self.comboBox_2.setSizePolicy(sizePolicy)
        self.comboBox_2.setMinimumSize(QtCore.QSize(15, 5))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        gradient = QtGui.QLinearGradient(0.0, 1.0, 1.0, 1.0)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(8, 148, 255))
        gradient.setColorAt(1.0, QtGui.QColor(24, 232, 253))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        gradient = QtGui.QLinearGradient(0.0, 1.0, 1.0, 1.0)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(8, 148, 255))
        gradient.setColorAt(1.0, QtGui.QColor(24, 232, 253))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        gradient = QtGui.QLinearGradient(0.0, 1.0, 1.0, 1.0)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(8, 148, 255))
        gradient.setColorAt(1.0, QtGui.QColor(24, 232, 253))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 128))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        gradient = QtGui.QLinearGradient(0.0, 1.0, 1.0, 1.0)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(8, 148, 255))
        gradient.setColorAt(1.0, QtGui.QColor(24, 232, 253))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        gradient = QtGui.QLinearGradient(0.0, 1.0, 1.0, 1.0)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(8, 148, 255))
        gradient.setColorAt(1.0, QtGui.QColor(24, 232, 253))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        gradient = QtGui.QLinearGradient(0.0, 1.0, 1.0, 1.0)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(8, 148, 255))
        gradient.setColorAt(1.0, QtGui.QColor(24, 232, 253))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 128))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        gradient = QtGui.QLinearGradient(0.0, 1.0, 1.0, 1.0)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(8, 148, 255))
        gradient.setColorAt(1.0, QtGui.QColor(24, 232, 253))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        gradient = QtGui.QLinearGradient(0.0, 1.0, 1.0, 1.0)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(8, 148, 255))
        gradient.setColorAt(1.0, QtGui.QColor(24, 232, 253))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        gradient = QtGui.QLinearGradient(0.0, 1.0, 1.0, 1.0)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(8, 148, 255))
        gradient.setColorAt(1.0, QtGui.QColor(24, 232, 253))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 128))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.PlaceholderText, brush)
        self.comboBox_2.setPalette(palette)
        self.comboBox_2.setStyleSheet("QScrollBar:vertical {\n"
"background-color: #0894FF;\n"
"width: 10px;\n"
"margin: 0px 0px 0px 0px;\n"
"}\n"
"QScrollBar::handle:vertical {\n"
"border-radius: 5px;\n"
"background: #18E8FD;\n"
"min-height: 48px;\n"
"}\n"
"\n"
"/* This remvoes the bottom button by setting the height to 0px */\n"
"QScrollBar::add-line:vertical {\n"
"height: 0px;\n"
"subcontrol-position: bottom;\n"
"subcontrol-origin: margin;\n"
"}\n"
"\n"
"/* This remvoes the top button by setting the height to 0px */\n"
"QScrollBar::sub-line:vertical {\n"
"height: 0px;\n"
"subcontrol-position: top;\n"
"subcontrol-origin: margin;\n"
"}\n"
"\n"
"/* need this to get rid of crosshatching on scrollbar background */\n"
"QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"background: none;\n"
"}\n"
"QComboBox{\n"
"border-width: 1px;        \n"
"border-style: solid;\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:1, x2:1, y2:1, stop:0 rgba(8, 148, 255, 255), stop:1 rgba(24, 232, 253, 255));\n"
"border-radius:5px;\n"
"border:none;\n"
"font:11pt;\n"
"font-weight:900;\n"
"padding:5px;\n"
"color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QComboBox::drop-down{\n"
"background-color: transparent;\n"
"    color:                      rgb(255, 255, 255);\n"
"    font-weight:            bold;\n"
"    padding:                    0px;\n"
"}\n"
"\n"
"QComboBox::down-arrow{\n"
" padding-right: 10px;\n"
"image: url(:/newPrefix/img/arrow-216-16.png);\n"
"color: rgb(255, 255, 255);\n"
"\n"
"}\n"
"QComboBox QAbstractItemView {\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0          rgba(24, 234, 253, 255), stop:0.75 rgba(8, 148, 255, 255));\n"
"border-radius:5px;\n"
"border:none;\n"
"color: rgb(255, 255, 255);\n"
"selection-background-color: rgb(44, 206, 255);\n"
"}")
        self.comboBox_2.setEditable(True)
        self.comboBox_2.setMaxVisibleItems(15)
        self.comboBox_2.setObjectName("comboBox_2")
        self.verticalLayout_2.addWidget(self.comboBox_2)
        self.gridLayout_9.addLayout(self.verticalLayout_2, 0, 0, 1, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab_3)
        self.groupBox_2.setStyleSheet("background-color: rgb(71, 71, 71);\n"
"font:11pt;\n"
"font-weight:900;\n"
"border:none;\n"
"border-radius:13px;\n"
"padding:7px;\n"
"")
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_3.setEnabled(False)
        self.lineEdit_3.setStyleSheet("border: 1px 1px 0px 1px;\n"
"color: rgb(255, 255, 255);\n"
"")
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.gridLayout_10.addWidget(self.lineEdit_3, 0, 0, 1, 1)
        self.toolButton_3 = QtWidgets.QToolButton(self.groupBox_2)
        self.toolButton_3.setEnabled(False)
        self.toolButton_3.setStyleSheet("QToolButton{\n"
"border-radius:16px;\n"
"background-color: rgb(48, 48, 48);\n"
"border:none;\n"
"font:  11pt;\n"
"}")
        self.toolButton_3.setIcon(icon2)
        self.toolButton_3.setObjectName("toolButton_3")
        self.gridLayout_10.addWidget(self.toolButton_3, 0, 2, 1, 1)
        self.listWidget = QtWidgets.QListWidget(self.groupBox_2)
        self.listWidget.setEnabled(False)
        self.listWidget.setStyleSheet("QScrollBar:vertical {\n"
"background-color: transparent;\n"
"width: 10px;\n"
"margin: 0px 0px 0px 0px;\n"
"}\n"
"QScrollBar::handle:vertical {\n"
"border-radius: 5px;\n"
"background: #18E8FD;\n"
"min-height: 48px;\n"
"}\n"
"\n"
"/* This remvoes the bottom button by setting the height to 0px */\n"
"QScrollBar::add-line:vertical {\n"
"height: 0px;\n"
"subcontrol-position: bottom;\n"
"subcontrol-origin: margin;\n"
"}\n"
"\n"
"/* This remvoes the top button by setting the height to 0px */\n"
"QScrollBar::sub-line:vertical {\n"
"height: 0px;\n"
"subcontrol-position: top;\n"
"subcontrol-origin: margin;\n"
"}\n"
"\n"
"/* need this to get rid of crosshatching on scrollbar background */\n"
"QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"background: none;\n"
"}\n"
"QListWidget{\n"
"color:rgb(255, 255, 255);\n"
"background-color: rgb(71, 71, 71);\n"
"font:11pt;\n"
"font-weight:900;\n"
"border:none;\n"
"border-radius:13px;\n"
"padding:5px;\n"
"\n"
"}\n"
"QListWidget::item::selected{\n"
"padding:-0px;\n"
"border-radius:7px;\n"
"background-color:  rgb(48, 48, 48);\n"
"color:rgb(255, 255, 255);\n"
"}\n"
"QListWidget::item{\n"
"padding:5px;\n"
"color:rgb(255, 255, 255);\n"
"}")
        self.listWidget.setDragDropMode(QtWidgets.QAbstractItemView.NoDragDrop)
        self.listWidget.setMovement(QtWidgets.QListView.Static)
        self.listWidget.setViewMode(QtWidgets.QListView.ListMode)
        self.listWidget.setModelColumn(0)
        self.listWidget.setObjectName("listWidget")
        self.gridLayout_10.addWidget(self.listWidget, 1, 0, 1, 3)
        self.toolButton_4 = QtWidgets.QToolButton(self.groupBox_2)
        self.toolButton_4.setEnabled(False)
        self.toolButton_4.setIcon(icon1)
        self.toolButton_4.setIconSize(QtCore.QSize(13, 13))
        self.toolButton_4.setObjectName("toolButton_4")
        self.gridLayout_10.addWidget(self.toolButton_4, 0, 1, 1, 1)
        self.toolButton_4.raise_()
        self.lineEdit_3.raise_()
        self.listWidget.raise_()
        self.toolButton_3.raise_()
        self.gridLayout_9.addWidget(self.groupBox_2, 3, 0, 1, 1)
        self.gridLayout_8.addLayout(self.gridLayout_9, 4, 0, 1, 1)
        self.tabWidget_2.addTab(self.tab_3, "")
        self.gridLayout_4.addWidget(self.tabWidget_2, 0, 1, 1, 1)
        self.tabWidget.addTab(self.tab, "")
        self.createprefix = QtWidgets.QWidget()
        self.createprefix.setStyleSheet("background-color: rgb(48, 48, 48);")
        self.createprefix.setObjectName("createprefix")
        self.gridLayout = QtWidgets.QGridLayout(self.createprefix)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_3 = QtWidgets.QLabel(self.createprefix)
        self.label_3.setStyleSheet("border-width: 1px;        \n"
"background-color: rgb(255, 16, 72);\n"
"border-radius:10px;\n"
"border:none;\n"
"font:11pt;\n"
"font-weight:900;\n"
"padding:1px;\n"
"color: rgb(255, 255, 255);")
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.label = QtWidgets.QLabel(self.createprefix)
        self.label.setStyleSheet("color: rgb(255, 255, 255);")
        self.label.setText("")
        self.label.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.label_4 = QtWidgets.QLabel(self.createprefix)
        self.label_4.setStyleSheet("border-width: 1px;        \n"
"border-style: solid;\n"
"background-color: rgb(255, 16, 72);\n"
"border-radius:10px;\n"
"border:none;\n"
"font:11pt;\n"
"font-weight:900;\n"
"padding:1px;\n"
"color: rgb(255, 255, 255);")
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.label_2 = QtWidgets.QLabel(self.createprefix)
        self.label_2.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.gridLayout.addLayout(self.verticalLayout, 2, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem2, 8, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.Createprefix = QtWidgets.QToolButton(self.createprefix)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Createprefix.sizePolicy().hasHeightForWidth())
        self.Createprefix.setSizePolicy(sizePolicy)
        self.Createprefix.setMinimumSize(QtCore.QSize(0, 70))
        self.Createprefix.setStyleSheet("QToolButton::checked{\n"
"border-radius:10px;\n"
"background-color:rgb(255, 16, 72);\n"
"}")
        self.Createprefix.setIconSize(QtCore.QSize(40, 40))
        self.Createprefix.setCheckable(True)
        self.Createprefix.setChecked(False)
        self.Createprefix.setAutoExclusive(True)
        self.Createprefix.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.Createprefix.setObjectName("Createprefix")
        self.horizontalLayout_2.addWidget(self.Createprefix)
        self.Selectwine = QtWidgets.QToolButton(self.createprefix)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Selectwine.sizePolicy().hasHeightForWidth())
        self.Selectwine.setSizePolicy(sizePolicy)
        self.Selectwine.setStyleSheet("QToolButton::checked{\n"
"border-radius:10px;\n"
"background-color: rgb(255, 16, 72);\n"
"}")
        self.Selectwine.setIconSize(QtCore.QSize(40, 40))
        self.Selectwine.setCheckable(True)
        self.Selectwine.setChecked(False)
        self.Selectwine.setAutoExclusive(True)
        self.Selectwine.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.Selectwine.setObjectName("Selectwine")
        self.horizontalLayout_2.addWidget(self.Selectwine)
        self.comboBox = QtWidgets.QComboBox(self.createprefix)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox.sizePolicy().hasHeightForWidth())
        self.comboBox.setSizePolicy(sizePolicy)
        self.comboBox.setAutoFillBackground(False)
        self.comboBox.setStyleSheet("QComboBox{\n"
"border-width: 1px;        \n"
"border-style: solid;\n"
"background-color: rgb(255, 16, 72);\n"
"border-radius:10px;\n"
"border:none;\n"
"font:11pt;\n"
"font-weight:900;\n"
"padding:5px;\n"
"color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QComboBox::drop-down{\n"
"background-color: transparent;\n"
"    color:                      rgb(255, 16, 72);\n"
"    font-weight:            bold;\n"
"    padding:                    10px;\n"
"}\n"
"\n"
"QComboBox::down-arrow{\n"
" padding-right: 10px;\n"
"image: url(:/newPrefix/img/arrow-216-16.png);\n"
"color: rgb(255, 255, 255);\n"
"\n"
"}\n"
"QComboBox QAbstractItemView {\n"
"background-color: rgb(255, 16, 72);\n"
"border-radius:10px;\n"
"color: rgb(255, 255, 255);\n"
"selection-background-color: rgb(255, 16, 72);\n"
"}")
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.horizontalLayout_2.addWidget(self.comboBox, 0, QtCore.Qt.AlignHCenter)
        self.Prefixload = QtWidgets.QToolButton(self.createprefix)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Prefixload.sizePolicy().hasHeightForWidth())
        self.Prefixload.setSizePolicy(sizePolicy)
        self.Prefixload.setStyleSheet("QToolButton::checked{\n"
"border-radius:10px;\n"
"background-color: rgb(255, 16, 72);;\n"
"}")
        self.Prefixload.setIconSize(QtCore.QSize(40, 40))
        self.Prefixload.setCheckable(True)
        self.Prefixload.setChecked(False)
        self.Prefixload.setAutoExclusive(True)
        self.Prefixload.setPopupMode(QtWidgets.QToolButton.InstantPopup)
        self.Prefixload.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.Prefixload.setObjectName("Prefixload")
        self.horizontalLayout_2.addWidget(self.Prefixload)
        self.gridLayout.addLayout(self.horizontalLayout_2, 1, 0, 1, 1)
        self.tabWidget.addTab(self.createprefix, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setMouseTracking(False)
        self.tab_2.setAutoFillBackground(False)
        self.tab_2.setStyleSheet("background-color: rgb(48, 48, 48);")
        self.tab_2.setObjectName("tab_2")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.tab_2)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.selectexe = QtWidgets.QToolButton(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.selectexe.sizePolicy().hasHeightForWidth())
        self.selectexe.setSizePolicy(sizePolicy)
        self.selectexe.setMinimumSize(QtCore.QSize(0, 40))
        self.selectexe.setStyleSheet("QToolButton::checked{\n"
"border-radius:10px;\n"
"background-color: rgb(255, 16, 72);\n"
"}")
        self.selectexe.setCheckable(True)
        self.selectexe.setChecked(False)
        self.selectexe.setAutoRepeat(True)
        self.selectexe.setAutoExclusive(True)
        self.selectexe.setObjectName("selectexe")
        self.verticalLayout_5.addWidget(self.selectexe)
        self.installexe = QtWidgets.QToolButton(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.installexe.sizePolicy().hasHeightForWidth())
        self.installexe.setSizePolicy(sizePolicy)
        self.installexe.setMinimumSize(QtCore.QSize(127, 40))
        self.installexe.setStyleSheet("QToolButton::checked{\n"
"border-radius:10px;\n"
"background-color: rgb(255, 16, 72);\n"
"}")
        self.installexe.setCheckable(True)
        self.installexe.setAutoExclusive(True)
        self.installexe.setObjectName("installexe")
        self.verticalLayout_5.addWidget(self.installexe)
        self.line = QtWidgets.QFrame(self.tab_2)
        self.line.setMinimumSize(QtCore.QSize(0, 20))
        self.line.setStyleSheet("")
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_5.addWidget(self.line)
        self.deleteitem = QtWidgets.QToolButton(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.deleteitem.sizePolicy().hasHeightForWidth())
        self.deleteitem.setSizePolicy(sizePolicy)
        self.deleteitem.setMinimumSize(QtCore.QSize(0, 40))
        self.deleteitem.setStyleSheet("QToolButton::checked{\n"
"border-radius:10px;\n"
"background-color: rgb(255, 16, 72);\n"
"}")
        self.deleteitem.setCheckable(True)
        self.deleteitem.setAutoExclusive(True)
        self.deleteitem.setObjectName("deleteitem")
        self.verticalLayout_5.addWidget(self.deleteitem)
        self.Winetricks = QtWidgets.QToolButton(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Winetricks.sizePolicy().hasHeightForWidth())
        self.Winetricks.setSizePolicy(sizePolicy)
        self.Winetricks.setMinimumSize(QtCore.QSize(0, 40))
        self.Winetricks.setStyleSheet("QToolButton::checked{\n"
"border-radius:10px;\n"
"background-color: rgb(255, 16, 72);\n"
"}")
        self.Winetricks.setCheckable(True)
        self.Winetricks.setAutoExclusive(True)
        self.Winetricks.setObjectName("Winetricks")
        self.verticalLayout_5.addWidget(self.Winetricks)
        self.WineCfg = QtWidgets.QToolButton(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.WineCfg.sizePolicy().hasHeightForWidth())
        self.WineCfg.setSizePolicy(sizePolicy)
        self.WineCfg.setMinimumSize(QtCore.QSize(0, 40))
        self.WineCfg.setStyleSheet("QToolButton::checked{\n"
"border-radius:10px;\n"
"background-color: rgb(255, 16, 72);\n"
"}")
        self.WineCfg.setCheckable(True)
        self.WineCfg.setAutoExclusive(True)
        self.WineCfg.setObjectName("WineCfg")
        self.verticalLayout_5.addWidget(self.WineCfg)
        self.toolButton_6 = QtWidgets.QToolButton(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolButton_6.sizePolicy().hasHeightForWidth())
        self.toolButton_6.setSizePolicy(sizePolicy)
        self.toolButton_6.setMinimumSize(QtCore.QSize(0, 40))
        self.toolButton_6.setStyleSheet("QToolButton::checked{\n"
"border-radius:10px;\n"
"background-color: rgb(255, 16, 72);\n"
"}")
        self.toolButton_6.setCheckable(True)
        self.toolButton_6.setAutoExclusive(True)
        self.toolButton_6.setObjectName("toolButton_6")
        self.verticalLayout_5.addWidget(self.toolButton_6)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem3)
        self.gridLayout_6.addLayout(self.verticalLayout_5, 0, 3, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setStyleSheet("background-color: rgb(71, 71, 71);\n"
"font:11pt;\n"
"font-weight:900;\n"
"border-radius:13px;\n"
"padding:7px;\n"
"\n"
"")
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_2.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_2.sizePolicy().hasHeightForWidth())
        self.lineEdit_2.setSizePolicy(sizePolicy)
        self.lineEdit_2.setMinimumSize(QtCore.QSize(0, 0))
        self.lineEdit_2.setMaximumSize(QtCore.QSize(10000, 40))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(71, 71, 71))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(71, 71, 71))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(71, 71, 71))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 128))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(71, 71, 71))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(71, 71, 71))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(71, 71, 71))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 128))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(71, 71, 71))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(71, 71, 71))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(71, 71, 71))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 128))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.PlaceholderText, brush)
        self.lineEdit_2.setPalette(palette)
        self.lineEdit_2.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.lineEdit_2.setStyleSheet("border: 1px 1px 0px 1px;\n"
"color: rgb(255, 255, 255);\n"
"")
        self.lineEdit_2.setText("")
        self.lineEdit_2.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.lineEdit_2.setCursorPosition(0)
        self.lineEdit_2.setCursorMoveStyle(QtCore.Qt.VisualMoveStyle)
        self.lineEdit_2.setClearButtonEnabled(False)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.gridLayout_3.addWidget(self.lineEdit_2, 3, 0, 1, 1)
        self.toolButton = QtWidgets.QToolButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolButton.sizePolicy().hasHeightForWidth())
        self.toolButton.setSizePolicy(sizePolicy)
        self.toolButton.setMinimumSize(QtCore.QSize(0, 0))
        self.toolButton.setBaseSize(QtCore.QSize(0, 0))
        self.toolButton.setStyleSheet("QToolButton{\n"
"border-radius:16px;\n"
"background-color: rgb(255, 16, 72);\n"
"border:none;\n"
"font:  11pt;\n"
"}")
        self.toolButton.setIcon(icon2)
        self.toolButton.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.toolButton.setAutoRaise(False)
        self.toolButton.setArrowType(QtCore.Qt.NoArrow)
        self.toolButton.setObjectName("toolButton")
        self.gridLayout_3.addWidget(self.toolButton, 3, 2, 1, 1)
        self.toolButton_2 = QtWidgets.QToolButton(self.groupBox)
        self.toolButton_2.setMinimumSize(QtCore.QSize(32, 0))
        self.toolButton_2.setText("")
        self.toolButton_2.setIcon(icon1)
        self.toolButton_2.setIconSize(QtCore.QSize(13, 13))
        self.toolButton_2.setPopupMode(QtWidgets.QToolButton.DelayedPopup)
        self.toolButton_2.setAutoRaise(False)
        self.toolButton_2.setObjectName("toolButton_2")
        self.gridLayout_3.addWidget(self.toolButton_2, 3, 1, 1, 1)
        self.listWidget_2 = QtWidgets.QListWidget(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listWidget_2.sizePolicy().hasHeightForWidth())
        self.listWidget_2.setSizePolicy(sizePolicy)
        self.listWidget_2.setMinimumSize(QtCore.QSize(510, 0))
        self.listWidget_2.setStyleSheet("QScrollBar:vertical {\n"
"background-color: transparent;\n"
"width: 25px;\n"
"margin: 0px 0px 0px 0px;\n"
"}\n"
"QScrollBar::handle:vertical {\n"
"border-radius: 5px;\n"
"background: rgb(48, 48, 48);\n"
"min-height: 48px;\n"
"}\n"
"\n"
"/* This remvoes the bottom button by setting the height to 0px */\n"
"QScrollBar::add-line:vertical {\n"
"height: 0px;\n"
"subcontrol-position: bottom;\n"
"subcontrol-origin: margin;\n"
"}\n"
"\n"
"/* This remvoes the top button by setting the height to 0px */\n"
"QScrollBar::sub-line:vertical {\n"
"height: 0px;\n"
"subcontrol-position: top;\n"
"subcontrol-origin: margin;\n"
"}\n"
"\n"
"/* need this to get rid of crosshatching on scrollbar background */\n"
"QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"background: none;\n"
"}\n"
"QListWidget{\n"
"color:rgb(255, 255, 255);\n"
"background-color: rgb(71, 71, 71);\n"
"font:11pt;\n"
"font-weight:900;\n"
"border:none;\n"
"border-radius:13px;\n"
"padding:5px;\n"
"\n"
"}\n"
"QListWidget::item::selected{\n"
"padding:-0px;\n"
"border-radius:7px;\n"
"background-color:  rgb(255, 16, 72);\n"
"color:rgb(255, 255, 255);\n"
"}\n"
"QListWidget::item{\n"
"padding:5px;\n"
"color:rrgb(255, 16, 72);\n"
"}")
        self.listWidget_2.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.listWidget_2.setProperty("showDropIndicator", False)
        self.listWidget_2.setDragDropMode(QtWidgets.QAbstractItemView.NoDragDrop)
        self.listWidget_2.setIconSize(QtCore.QSize(13, 13))
        self.listWidget_2.setProperty("isWrapping", False)
        self.listWidget_2.setObjectName("listWidget_2")
        self.gridLayout_3.addWidget(self.listWidget_2, 4, 0, 1, 1)
        self.gridLayout_6.addWidget(self.groupBox, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setStyleSheet("background-color: rgb(48, 48, 48);")
        self.tab_4.setObjectName("tab_4")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.tab_4)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.toolButton1 = QtWidgets.QToolButton(self.tab_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolButton1.sizePolicy().hasHeightForWidth())
        self.toolButton1.setSizePolicy(sizePolicy)
        self.toolButton1.setStyleSheet("QToolButton::checked{\n"
"border-radius:5px;\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:1, x2:1, y2:1, stop:0 rgba(255, 129, 25, 255), stop:1 rgba(255, 0, 0, 255));\n"
"}")
        self.toolButton1.setCheckable(True)
        self.toolButton1.setAutoRepeat(True)
        self.toolButton1.setAutoExclusive(True)
        self.toolButton1.setObjectName("toolButton1")
        self.gridLayout_7.addWidget(self.toolButton1, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_4, "")
        self.horizontalLayout_3.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.actionrty = QtWidgets.QAction(MainWindow)
        icon = QtGui.QIcon.fromTheme("folder")
        self.actionrty.setIcon(icon)
        self.actionrty.setObjectName("actionrty")
        self.actionEnglish = QtWidgets.QAction(MainWindow)
        self.actionEnglish.setObjectName("actionEnglish")
        self.action_2 = QtWidgets.QAction(MainWindow)
        self.action_2.setObjectName("action_2")

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        self.tabWidget_2.setCurrentIndex(0)
        self.comboBox_2.setCurrentIndex(-1)
        self.comboBox.setCurrentIndex(0)
        self.toolButton_2.clicked.connect(self.lineEdit_2.clear)
        self.toolButton_4.clicked.connect(self.lineEdit_3.clear)
        self.toolButton_8.clicked.connect(self.lineEdit_4.clear)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.selectexe, self.installexe)
        MainWindow.setTabOrder(self.installexe, self.comboBox)
        MainWindow.setTabOrder(self.comboBox, self.Prefixload)
        MainWindow.setTabOrder(self.Prefixload, self.Createprefix)
        MainWindow.setTabOrder(self.Createprefix, self.Selectwine)
        MainWindow.setTabOrder(self.Selectwine, self.deleteitem)
        MainWindow.setTabOrder(self.deleteitem, self.Winetricks)
        MainWindow.setTabOrder(self.Winetricks, self.WineCfg)
        MainWindow.setTabOrder(self.WineCfg, self.toolButton_6)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Games4Linux"))
        self.toolButton_8.setText(_translate("MainWindow", "..."))
        self.toolButton_9.setText(_translate("MainWindow", "..."))
        self.lineEdit_4.setPlaceholderText(_translate("MainWindow", "Поиск"))
        self.toolButton_10.setText(_translate("MainWindow", "Запустить"))
        self.toolButton_7.setText(_translate("MainWindow", "Удалить"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_5), _translate("MainWindow", "Моя библиотека"))
        self.Installscript.setText(_translate("MainWindow", "Установка"))
        self.lineEdit_3.setPlaceholderText(_translate("MainWindow", "Поиск"))
        self.toolButton_3.setText(_translate("MainWindow", "..."))
        self.toolButton_4.setText(_translate("MainWindow", "..."))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_3), _translate("MainWindow", "Онлайн библиотека"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Библиотека"))
        self.label_3.setText(_translate("MainWindow", "Путь к префиксу:"))
        self.label_4.setText(_translate("MainWindow", "Путь к wine:"))
        self.Createprefix.setText(_translate("MainWindow", "Создать и выбрать\n"
" префикс"))
        self.Selectwine.setText(_translate("MainWindow", "Выбрать wine"))
        self.comboBox.setCurrentText(_translate("MainWindow", "win64"))
        self.comboBox.setItemText(0, _translate("MainWindow", "win64"))
        self.comboBox.setItemText(1, _translate("MainWindow", "win32"))
        self.Prefixload.setText(_translate("MainWindow", "сконфигурировать \n"
"префикс"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.createprefix), _translate("MainWindow", "Создание"))
        self.selectexe.setText(_translate("MainWindow", "Выбрать .exe"))
        self.installexe.setText(_translate("MainWindow", "Установка"))
        self.deleteitem.setText(_translate("MainWindow", "Удалить"))
        self.Winetricks.setText(_translate("MainWindow", "Winetricks"))
        self.WineCfg.setText(_translate("MainWindow", "Winecfg"))
        self.toolButton_6.setText(_translate("MainWindow", "..."))
        self.lineEdit_2.setPlaceholderText(_translate("MainWindow", "Поиск"))
        self.toolButton.setText(_translate("MainWindow", "Поиск"))
        self.toolButton_2.setShortcut(_translate("MainWindow", "Backspace"))
        self.listWidget_2.setWhatsThis(_translate("MainWindow", "<html><head/><body><p>ваапвап</p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Префиксы"))
        self.toolButton1.setText(_translate("MainWindow", "обновление "))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", "Настройки"))
        self.actionrty.setText(_translate("MainWindow", "rty"))
        self.actionrty.setShortcut(_translate("MainWindow", "Backspace"))
        self.actionEnglish.setText(_translate("MainWindow", "English"))
        self.action_2.setText(_translate("MainWindow", "Русский"))
import resource_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
