#!/bin/sh
WINEARCH="win64" WINEPREFIX="/home/dron/Prefix x64" WINE=/home/dron/GamesForLinux/code_files/runner/lutris-lol-5.5-2-x86_64/bin/wine  /home/dron/GamesForLinux/code_files/winetricks &
WINEARCH=win64 WINEPREFIX="/home/dron/Prefix x64" /home/dron/GamesForLinux/code_files/runner/lutris-lol-5.5-2-x86_64/bin/wine  winecfg &
/home/dron/Prefix x64/drive_c/
WINEARCH=win64 WINEPREFIX="/home/dron/Prefix x64" /home/dron/GamesForLinux/code_files/runner/lutris-lol-5.5-2-x86_64/bin/wine explorer "