#!/bin/sh
WINEARCH=win64 WINEPREFIX="/home/dron/Lol x64" /home/dron/.local/share/lutris/runners/wine/lutris-lol-5.5-2-x86_64/bin/wine "uninstaller"
/home/dron/GamesForLinux/code_files/icon/Lol x64 | League of Legends