#!/bin/sh
WINEARCH=win64 WINEPREFIX="/home/dron/Prefix x64" /home/dron/GamesForLinux/code_files/runner/lutris-lol-5.5-2-x86_64/bin/wine explorer "uninstaller"
/home/dron/GamesForLinux/code_files/icon/Prefix x64 | Ангелы Тьмы - Маскарад Теней